module.exports = {
  // fake values here, TODO: fix typo
  "auth0_aws_assests_access_key_id": "FAKEFAKEFAKEFAKEFAKE",
  "auth0_aws_assests_access_secret_key": "fakefakefakefakefakefakefakefakefakefake",
  "auth0_aws_assests_s3_bucket": "mozilla-infosec-auth0-dev-rule-assets",

  // fake values here
  "duo_ikey_mozilla": "FAKEFAKEFAKEFAKEFAKE",
  "duo_skey_mozilla": "fakefakefakefakefakefakefakefakefakefake",
  "duo_apihost_mozilla": "api-fakehost.duosecurity.com",

  "iam_well_known": "https://auth.allizom.org/.well-known/mozilla-iam",

  "github_enterprise_wiki_url": "https://wiki.mozilla.org/GitHub/SAML_issues?auth=dev",
  "personapi_url": "https://person.api.dev.sso.allizom.org",
  "personapi_client_id": "fakefakefakefakefakefakefakefake",
  "personapi_client_secret": "fakefakefakefakefakefakefakefakefakefakefakefakefakefakefakefake",
  "personapi_oauth_url": "https://auth.mozilla.auth0.com/oauth/token",
  // these were generated simply for tests, and are not used anywhere else
  "jwt_msgs_rsa_skey": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdWlsUXZtbzRNcEtJT3B1empDSFJaajRGamk3dFJTMGhCeDYwRDV5bmZoRVhtMmVOCjhnQ1Z5RlBQc3VYd0YvM1I1aU5tbTk3VHJDQVVLWnJOUHZQbjlXc0ZvSGZIeXBBZUUwTVlVNC9RSEZNRk9XWmoKQ1I2WGZ1Z0tIaTZUelI4YWcxRW5kWXVkNzhzN2dMaFp6UHJkcWhoQkRKcS9vaTVPMDhBNWdiWTZFbEFTVVBMWApZYTNDTUVoMGIzbWp4TUYxcHBEay9yeUs1TDRoRlpiUzhJQlRYMHkyUldsRWpBTk13MVBzb3VnTmlRS1FQdm1wCmRicVBLTnBIZkxHcjJXdkoxeGI1OWJuT0JvRmp1d1JrOUlhQkRnNXhINVdsYjZGd2piN1B3WnRqRUkvTkZXMVcKaU43Ujl4a3pzY0pJYXVBT0NDZndkOXF0UWhHVFNvU1c4b2xOQlFJREFRQUJBb0lCQUc0SmtkS2IwcEFDRVVnagpWS1BXTVlJdjB2VFNSQ21KbldZcC9lRGtoaFI4WWVuWDhnMUR6MFZVVlFhMzU0MG0yUFVobzdzcW9RK3kvbmdCCktxUzFZenlyZiszMEgwSmFvWXhkTW5uaUhlOUFHMnhzV3NtL0xXazBHeGJ3RFNsSDQxSVBuRFZjeTRROEt2WFIKQWpPcGJYRG5XVHZzRkszMmxWMlExKzBXRzRsS2pOc1NnaU1ZNG5ORUIvVkxWOVU1RUFRRXIwWllScjk1R2RLZwpsM3FDcjhDelhZc0Z2bzJZRHVqWjNlV202OHdDOW95TGh4WGVEQllscEo1VDNyOTRCN2dEL1c0VGNjSUFYS3VQCnA0R2NPT3M0Nm4yemtQUFpOTUt6Z1NvbTA5OTNvWmNMUlJPb0cyVVpKQ2xxYy84NzBGaUMyVzEwK0lOaEtrWGsKaFBmendsa0NnWUVBNDZLZkhHSGtuRG5WbW9CTWFpb2NHZ1BCcURnTkxveUdpNHBhYXdBdUYrL3p1RmY4N1RZegpoTk4vNXpNL2tsTGxSNHRtZ2hEUHcvU0w4cGkrcFVSdEMwNmRKNjRpRERIbmVrdDRLQVZVdS84a1lTeTl5aWpnCnlzRUlmbG92d25Pc252aHhBcVkvR1FEMmRRVFgxUVFkK21uUEN1UFJUQlZpTFlzdkhYL1RkS3NDZ1lFQTBWdTIKT284YXBiUTNFQS8xblJrUGdqanpNVHNhY0FhL29hQkM3enZlVktGdXdqbEVYTSs0bnhxQU1iQ1ozZStwcTlVSwpMT1YvY2hTeFZjYXlacFRZTlhqNWFLTENBMU1Jd2lSaGJ6Q3pHNWYyWWVjeTJlczhyQU1qVlNqdU5nNHpNN25hClBZQzBYNncxb3dXVnA0Z0RhVGtPdVRHTjNmRFFkSmluM1F4YVpROENnWUVBcSt6MU0yQ1VZNUlpekhBK1JxakwKVkxLbG4wSEdZdlByNHBSNk9mcUcxYmw3WUMzRWIvelI2RzQ5V2dlUTZoa0Y1b1ZZeEwraHpDUjFWcU1heW9QbAp2L1orSjZ3VE54YXg5K0hzUEgzYVE2c3VkTjV2OGJIeUpmQ3BVNVVXSVUxd2dSaXZjZ3JSK1RhSzdsTGNHSnpsCmIyNWUyNkM1UVRlZFVUeWdOeTJHTGNVQ2dZRUF1YzRmYU5GZzRQZVVkdGp6THozeW1heFppYlBldnRYK2RUOTYKcUVBR0RpNUgwbkJvejhZN0lGbXd0R2o3NWhDeUVTSytLU0oxZlpZSDNReS9nSE5SZ0FPaHRzL2NTSDhGSXVpTwo0TlBqNGZWNFlXT0RxZ3d3aUtrd1RvQkpDZ2lJUUx3TmlOQVZSV1BkSnBYcVFBbGluWnhhQ05xR0FoZWJxaDloCnU3a2U4TmtDZ1lBYUR5K1praE5ZaDQ0QlVNbnNHZVJEYkhQbHhyb1RaL0RxYlpNdElKZitMWThscm9sYmNrTm8KTGNJVEhPckV4UjNTRXhadktSNGFUbTlIbFh5eU1NSVdraWlzUkhQMVJ6bTMwR2tVb3pUZ2ROMXZEQk5MZWlYawp1bVlvcW40V1hVdEpSUGtRdktIaWpyVzNiL01iQWdnck5maCtYcVlKbzA5aEc1bS81SVRKWGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=",
  "jwt_msgs_rsa_pkey": "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1aWxRdm1vNE1wS0lPcHV6akNIUgpaajRGamk3dFJTMGhCeDYwRDV5bmZoRVhtMmVOOGdDVnlGUFBzdVh3Ri8zUjVpTm1tOTdUckNBVUtack5QdlBuCjlXc0ZvSGZIeXBBZUUwTVlVNC9RSEZNRk9XWmpDUjZYZnVnS0hpNlR6UjhhZzFFbmRZdWQ3OHM3Z0xoWnpQcmQKcWhoQkRKcS9vaTVPMDhBNWdiWTZFbEFTVVBMWFlhM0NNRWgwYjNtanhNRjFwcERrL3J5SzVMNGhGWmJTOElCVApYMHkyUldsRWpBTk13MVBzb3VnTmlRS1FQdm1wZGJxUEtOcEhmTEdyMld2SjF4YjU5Ym5PQm9GanV3Ums5SWFCCkRnNXhINVdsYjZGd2piN1B3WnRqRUkvTkZXMVdpTjdSOXhrenNjSklhdUFPQ0Nmd2Q5cXRRaEdUU29TVzhvbE4KQlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==",
};
