function (user, context, callback) {
  // /!\ DO NOT EDIT THIS FILE /!\
  // Please use http://github.com/mozilla-iam/auth0-rules instead
  var WHITELIST = [
    'moc-sso-monitoring@mozilla.com', // MOC see https://bugzilla.mozilla.org/show_bug.cgi?id=1423903
    'moc+servicenow@mozilla.com' // MOC see https://bugzilla.mozilla.org/show_bug.cgi?id=1423903
    ];
  if (!user.email_verified) {
    console.log('duosecurity: user primary email NOT verified, refusing login for '+user.email);
    return callback(null, user, global.postError('notingroup', context));
  }
  if (WHITELIST.indexOf(user.email) >= 0) {
    console.log('duosecurity: whitelisted account '+user.email+', no 2FA check performed');
    return callback(null, user, context);
  }
  // LDAP group okta_mfa requires MFA authentication everywhere.
  if (context.connectionStrategy === 'ad') {
    context.multifactor = {
      provider: 'duo',
      ikey: configuration.duo_ikey_mozilla,
      skey: configuration.duo_skey_mozilla,
      host: configuration.duo_apihost_mozilla,

      // optional:
      // Force DuoSecurity everytime this rule runs. Defaults to false.
      // If accepted by users the cookie lasts for 30 days - i.e. 30 days MFA session (this cannot be changed)
      ignoreCookie: false,
      username: user.email,
    };
  }
  callback(null, user, context);
}
