function (user, context, callback) {
  // /!\ DO NOT EDIT THIS FILE /!\
  // Please use http://github.com/mozilla-iam/auth0-rules instead

  // Applications that are restricted
  var APPS = ['mozdefqa1.private.scl3.mozilla.com'];
  // LDAP groups allowed to access these applications
  var ALLOWED_GROUPS = ['vpn_mozdef'];

  if (APPS.indexOf(context.clientName) !== -1) {
    var groupHasAccess = ALLOWED_GROUPS.some(
      function (group) {
        if (!user.groups)
          return false;
        return user.groups.indexOf(group) >= 0;
    });
    if (groupHasAccess) {
     return callback(null, user, context);
    } else {
     context.redirect = {
       url: "https://sso.mozilla.com"
     };
     return callback(null, null, context);
    }
  }
  callback(null, user, context);
}
